channels:
    -   conda-forge
    
dependencies:
    -   python
    -   numpy
    -   scipy
    -   scikit-learn
    -   matplotlib
    -   pytorch 
    -   pandas
    -   seaborn
    -   pingouin
    -   cython
    -   pip
    -   pip:
            -   jupyter_contrib_nbextensions            
            -   jupyter_nbextensions_configurator
            -   cffi_magic
            -   opencv-contrib-python
            -   moviepy
            -   pygame
            -   pillow
            -   concurrent-log-handler
            -   openpyxl
            -   requests
            -   selenium
            -   scrapy
            -   jieba
            -   lxml
    