channels:
    -   conda-forge
    
dependencies:
    -   python
    -   numpy
    -   scipy
    -   scikit_learn
    -   matplotlib
    -   pytorch 
    -   pandas
    -   seaborn
    -   pingouin
    -   cython
    -   pip
    -   pip:
            -   cffi_magic
    