channels:
    -   conda-forge
    
dependencies:
    -   python
    -   numpy
    -   scipy
    -   scikit-learn
    -   matplotlib
    -   pytorch 
    -   pandas
    -   seaborn
    -   pingouin
    -   cython
    -   pip
    -   pip:
            -   jupyter_contrib_nbextensions            
            -   jupyter_nbextensions_configurator
            -   cffi_magic
            -   opencv-contrib-python
            -   moviepy
            -   pygame
            -   pillow
            -   concurrent-log-handler
            -   openpyxl
            -   requests
            -   selenium
            -   scrapy
            -   jieba
            -   lxml
            -   alembic
            -   async-generator
            -   attrs
            -   backcall
            -   beautifulsoup4
            -   bleach
            -   blinker
            -   bokeh
            -   Bottleneck
            -   brotlipy
            -   certifi
            -   certipy
            -   cffi
            -   chardet
            -   click
            -   cryptography
            -   cycler
            -   Cython
            -   cytoolz
            -   dask
            -   decorator
            -   defusedxml
            -   dill
            -   dlai-tools
            -   entrypoints
            -   fastcache
            -   fsspec
            -   gmpy2
            -   h5py
            -   HeapDict
            -   idna
            -   imageio
            -   importlib-metadata
            -   jedi
            -   joblib
            -   json5
            -   jsonschema
            -   kiwisolver
            -   locket
            -   Mako
            -   MarkupSafe
            -   matplotlib
            -   mistune
            -   mpmath
            -   msgpack
            -   networkx
            -   numexpr
            -   oauthlib
            -   olefile
            -   packaging
            -   pamela
            -   pandas
            -   pandocfilters
            -   parso
            -   partd
            -   patsy
            -   pexpect
            -   pickleshare
            -   Pillow
            -   protobuf
            -   ptyprocess
            -   pycosat
            -   pycparser
            -   pycurl
            -   Pygments
            -   PyJWT
            -   pyOpenSSL
            -   pyparsing
            -   pyrsistent
            -   PySocks
            -   python-dateutil
            -   python-json-logger
            -   pytz
            -   PyWavelets
            -   PyYAML
            -   pyzmq
            -   requests
            -   ruamel-yaml
            -   ruamel.yaml.clib
            -   scikit-image
            -   scikit-learn
            -   scipy
            -   seaborn
            -   Send2Trash
            -   six
            -   sortedcontainers
            -   soupsieve
            -   SQLAlchemy
            -   statsmodels
            -   sympy
            -   tables
            -   tblib
            -   terminado
            -   testpath
            -   toolz
            -   tornado
            -   tqdm
            -   traitlets
            -   urllib3
            -   vincent
            -   wcwidth
            -   webencodings
            -   xlrd
            -   zict
            -   zipp           