#!/bin/bash

# run matplotlib once to generate the font cache
python3 -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"
test -e test.png && rm test.png

# install JupyterLab extension
# jupyter labextension install @jupyterlab/latex

# start xwindow
echo "export DISPLAY=:0" >> $HOME/.bashrc 

echo "#!/bin/bash" > $HOME/startXWindow
echo "'/usr/bin/Xvfb :0 -ac -screen 0 1280x960x24 &" >> $HOME/startXWindow
echo "x11vnc -noxdamage -forever -shared -display :0 -passwd 123456 &" >> $HOME/startXWindow
echo "LANG=en_US.UTF-8 /usr/bin/jwm -display :0 &" >> $HOME/startXWindow
chmod a+x $HOME/startXWindow
